apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  namespace: default
data:
  Caddyfile: |
    :80 { 
      proxy / homepage
      proxy /graphql hasura {
        without /graphql
        websocket
      }
      proxy /graphiql graphiql {
        without /graphiql
      }
      proxy /graphql/react react-apollo {
        without /graphql/react
      }
    }
