apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  namespace: default
data:
  Caddyfile: |
    :80 { 
      proxy / homepage
      proxy /graphql hasura
      proxy /graphiql grahiql
      proxy /graphql/react react-apollo
    }
